FROM mysql/mysql-server:latest

COPY my.cnf /etc/mysql/conf.d/
RUN chmod 644 /etc/mysql/conf.d/my.cnf

COPY ./scripts/ /docker-entrypoint-initdb.d/

ENV TZ=America/Edmonton

HEALTHCHECK CMD mysqladmin ping -h localhost
